version: '3.7'

services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - $HOME/searxng/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - $HOME/searxng/caddy/data:/data
      - $HOME/searxng/caddy/config:/config
    environment:
      - SEARXNG_HOSTNAME=XXXeditiermichXXX
      - SEARXNG_TLS=XXXeditiermichXXX
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
      - $HOME/searxng/srv:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=XXXeditiermichXXX
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default
